apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: grpc-server
  namespace: linkerd-demo
  labels: 
    app: grpc-server
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: grpc-server
  template: 
    metadata: 
      labels: 
        app: grpc-server
    spec: 
      containers: 
      - name: grpc-server
        image: carlostorres10/grpc_grpc-server:latest
        ports: 
          - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata: 
  name: grpc-server
  namespace: linkerd-demo
spec: 
  selector: 
    app: grpc-server
  ports: 
    - protocol: TCP 
      targetPort: 9000
      port: 9000
