apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: broker
  namespace: linkerd-demo
  labels: 
    app: broker
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: broker
  template: 
    metadata: 
      labels: 
        app: broker
    spec: 
      containers: 
      - name: broker
        image: confluentinc/cp-kafka:5.5.1
        ports: 
        - containerPort: 29092
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://broker:29092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
          value: "0"
        - name: KAFKA_JMX_PORT
          value: "9101"
        - name: KAFKA_CREATE_TOPICS
          value: "whatever"
        
---
apiVersion: v1
kind: Service
metadata: 
  name: broker
  namespace: linkerd-demo
spec: 
  selector: 
    app: broker
  ports: 
    - protocol: TCP 
      port: 29092
      targetPort: 29092

