apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: grpc-client
  namespace: linkerd-demo
  labels: 
    app: grpc-client
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: grpc-client
  template: 
    metadata: 
      labels: 
        app: grpc-client
    spec: 
      containers: 
      - name: grpc-client
        image: carlostorres10/grpc_grpc-client:latest
        ports: 
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata: 
  name: grpc-client
  namespace: linkerd-demo
spec: 
  selector: 
    app: grpc-client
  ports: 
    - protocol: TCP 
      targetPort: 8000
      port: 80
