apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: redis-publisher
  namespace: linkerd-demo
  labels: 
    app: redis-publisher
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: redis-publisher
  template: 
    metadata: 
      labels: 
        app: redis-publisher
    spec: 
      containers: 
      - name: redis-publisher
        image: marckomatic/redis-publisher
        ports: 
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata: 
  name: redis-publisher
  namespace: linkerd-demo
spec: 
  selector: 
    app: redis-publisher
  type: LoadBalancer
  ports: 
    - protocol: TCP 
      port: 5001
      targetPort: 5001
      nodePort: 31002
