apiVersion: networking.k8s.io/v1
kind: Ingress
metadata: 
  name: general-ingress 
  namespace: linkerd-demo
spec: 
  rules: 
    - host: realworks.tech
      http:
        paths:
        - path: /*
          backend:
            serviceName: redis-publisher
            servicePort: 5001