apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata: 
  name: general-ingress 
  namespace: linkerd-demo
  annotations:
    kubernetes.io/ingress.class: gce
spec: 
  rules: 
    - host: realworks.tech
      http:
        paths:
        - path: /*
          backend:
            serviceName: redis-publisher
            servicePort: 5001